### ISSUE TITLE
ePub / none Amazon version of your book

### ISSUE THREAD

**Issue by AxelRHD** [bigskysoftware/hypermedia-systems#102]
I really like your book and it would be great to read it on my e-reader (no Kindle).

Would it be possible to get a paid version (also Adobe DRM possible) on another platform than Amazon (Leanpub for example)?

Thanks a lot.

**Comment by codetalcott** [comment]
The book is published through Kindle, so alternative paid versions are unlikely. It is possible to download the full online version as a pdf and read it on any platform. Look for the "Entire book in one page" link in the online Table of Contents.
