### ISSUE TITLE
"Write useful link text" do/don't example mixed up?

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#11]
In the [write useful link text](https://hypermedia.systems/book/hypermedia-systems/#_write_useful_link_text) section, it says:

> Wherever possible, the text of a link should describe what the link points to without much context needed. Of course, you might need to alter it to fit a sentence structure, but you should avoid links that don’t give information other than “this is a link”.

> Do | Don’t
> -- | --
> For user records, [click here] | [User records]

I think it's probably as simple as the "do" and "don't" examples being the wrong way around.

If not, the "do" example doesn't fit the guidance since **link text** "click here" does not "describe what the link points to without much context needed".

**Comment by dz4k** [comment]
You're right that the examples are switched. I'll take care of it when I'm completing that chapter.
