### ISSUE TITLE
Chapter 9 fix / Are Pull Requests being reviewed?

### ISSUE THREAD

**Issue by lucaslugao** [bigskysoftware/hypermedia-systems#110]
In June 2023, I submitted a PR featuring a small yet functionally significant adjustment to chapter 9: [https://github.com/bigskysoftware/hypermedia-systems/pull/85](https://github.com/bigskysoftware/hypermedia-systems/pull/85).

Subsequently, in November 2023, a different individual resubmitted the same correction, along with a minor code indentation improvement: [https://github.com/bigskysoftware/hypermedia-systems/pull/107](https://github.com/bigskysoftware/hypermedia-systems/pull/107).

Could you provide any insight as to why neither of these PRs has been reviewed or rejected?

Thank you!

**Comment by adamstep** [comment]
Hi @lucaslugao , sorry for the delay. While I didn't write that particular chapter, I will take a look at the PR this week, thanks!

**Comment by codetalcott** [comment]
merged, at last.
