### ISSUE TITLE
Typo in Chapter 8 "Canceling a Request Using htmx:abort"

### ISSUE THREAD

**Issue by intoxx** [bigskysoftware/hypermedia-systems#113]
Typo at https://hypermedia.systems/deep-htmx/
It should be written **enabled** instead of **disabled** *(see picture)*.
![image](https://github.com/bigskysoftware/hypermedia-systems/assets/8056454/1fd5b34c-cb11-4c2a-926c-a74393b96142)

**Comment by ramiro** [comment]
Fixed in #115.

This issue can be closed.

**Comment by mvolkmann** [comment]
This issue should be closed, but I can't close it.
