### ISSUE TITLE
Book written with a mix of "I" and "We"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#12]
There's some inconsistency with "I" and "We" in the book.

**In some sections, the author writes in a singular style ("I"), a few examples:**

> For the remaining templates I am going to omit the layout directive

> I am the first to admit that conversations around REST and which HTTP Action is right for a given operation can become very tedious

> Again, this is not a CSS book and I am not going to go deeply into the details of CSS transitions

**And for others, it's a plural style ("We"), a few examples:**

> Well, we are glad you asked

> We are going to talk more about the various ways that htmx enhances regular HTTP requests

> We are not hypermedia puritans and encourage you to learn many different web technologies

**This could confuse the reader, because "we" is also used extensively when working through exercises _with_ the reader, e.g.:**

> we are going to create a simple contact management web application called Contacts.app

> We are using the Jinja2 templating language

> we are seeing the flexibility of hypermedia in action.

I can totally see how this happens with multiple contributors, I'd suggest:

1. decide on one and update the other references; or
2. have different authors for different chapters (or sections) so it's clear who "I" refers to, and then that also allows the collective "we" to refer to all the authors but it could still cause some confusion in a section where "we" is used in exercises with the reader

(Note: I've only given a few examples for each, not an exhaustive list)

**Comment by 1cg** [comment]
Good catch, since the publisher canceled the book I would like to switch to "we" from "I" in all places.

@adamstep I didn't touch your chapters, would you be OK updating your text to use "we"?  Fine if no.

**Comment by adamstep** [comment]
> @adamstep I didn't touch your chapters, would you be OK updating your text to use "we"? Fine if no.

Yes, I will update my chapters for consistency.

**Comment by adamstep** [comment]
Fixed in e6320ebd960b46018c5d58f86074d11a570d1473

**Comment by 1cg** [comment]
thank you @adamstep ! and thank you @elliottinvent  for all the feedback!
