### ISSUE TITLE
Ch12: code for omitted hyperview <styles> 

### ISSUE THREAD

**Issue by r3imer** [bigskysoftware/hypermedia-systems#125]
Trying to follow the book and rebuilding with `C#` (Link to [My Project](https://github.com/r3imer/hypermedia-systems)).

In Chapter 12 ([Building a contacts app with hyperview](https://hypermedia.systems/building-a-contacts-app-with-hyperview/)) the Style-Code is `<styles><!-- omitted for brevity --></styles>`.  

I just wanted to ask, where I can find this code or if it is available?

**Comment by adamstep** [comment]
Yes, the code is available, here are some quick links:

Also, the code from the book is available online as well, you can check out these branches:

- Basic contacts app implementation: https://github.com/adamstep/contact-app/commits/adam/hv3/
- Add support for phone calls and email: https://github.com/adamstep/contact-app/commits/adam/hv3-comms/
- Add support for toast messages: https://github.com/adamstep/contact-app/commits/adam/hv3-messages/
- Add swipe gesture support: https://github.com/adamstep/contact-app/commits/adam/hv3-swipe/

In particular, the initial styles are available here: https://github.com/adamstep/contact-app/blob/f1a5858a792cdbeaeee6bd064f2f60a1e71fe5d1/templates/hv/layout.xml

**Comment by r3imer** [comment]
Thx
