### ISSUE TITLE
Text is wrong - in So What Isn’t Hypermedia section

### ISSUE THREAD

**Issue by mmeroberts** [bigskysoftware/hypermedia-systems#126]
The details of exactly what the updateUI() function **does** aren’t important for our discussion.

Does is unnecessary

**Comment by codetalcott** [comment]
Thanks for the suggestion. There are some unnecessary words there, but I think the sentence fits the authors' conversational style.

**Comment by mmeroberts** [comment]
I only picked it up as I was using a read aloud tool and this sentence just
sounded very strange to hear.
