### ISSUE TITLE
Possible inconsistency with HTTP Method / HTTP Action

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#13]
There seems to be an inconsistency in how `GET`, `POST`, `PUT` etc are referred to. 

**Sometimes it's `HTTP Method`:** 

> The replacement content will be fetched with the `GET` HTTP method

>  using different HTTP methods: a `GET` to `/contacts/<contact_id>/edit` will return a form

> When building a Hypermedia-Driven Application, you want, instead, to go "`with the grain`" of The Web and use HTTP methods and response codes as they were designed to be used.

**Other times it's `HTTP Action`:**

> From a technical perspective, all the updates are done with the `POST` HTTP action

>  HTML could be extended so that it could access these missing three HTTP actions, `PUT`, `PATCH` and `DELETE`.

> As usual, this is pretty straight forward: we simply create a new handler for the `DELETE` HTTP Action

You guys are the hypermedia wizards, and I'm not claiming to be an expert here, but my understanding is that these are [HTTP Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) (or more formally "HTTP Request Methods") but `GET` and `POST` correspond to an HTML form action?

**Comment by 1cg** [comment]
You are right, I tend to shift back and forth in casual language, but we should standardize on Method, which is correct.

I wish the form attribute had been `method` instead
