### ISSUE TITLE
Mobile Code missing? (xml templates)

### ISSUE THREAD

**Issue by adamwoolhether** [bigskysoftware/hypermedia-systems#137]
I know this isn't a big deal, but i'm painstakingly trying to define my styles to match the examples in the book :)

All styles are omitted from book examples, understandably. Would be great it it were uploaded here, for easy comparison/checking.

**Comment by adamstep** [comment]
Hi @adamwoolhether , all of the code is available in a Github repository, including the styles and templates for each chapter. See this issue for the the full list: https://github.com/bigskysoftware/hypermedia-systems/issues/125

I should add this to the main website to make it easier to find!

**Comment by adamwoolhether** [comment]
@adamstep Thanks a ton. Really helps me getting moving towards the direction i want. Cheers!

**Comment by adamwoolhether** [comment]
One thing I'm still having difficult with is implementing the actual phone/email funcs from`react-native-communications`

I've created `phone.js` `email.js` and `HyperviewScreen.js`, placed them in `hyperview/demo/src` folder, rebuilt app, but clicking the behaviors in mobile app shows error:
```
 WARN  No behavior registered for action "open-phone"
 WARN  No behavior registered for action "open-email"
```

I've also tried registering the behaviors in `hyperview/demo/src/HyperviewScreen.tsx` file:
```
import OpenPhone from './phone';
import OpenEmail from './email';

HyperviewScreen.Behaviors = [OpenPhone, OpenEmail];

```

But the result is the same 🤔

**Comment by adamstep** [comment]
Hi, I got an email about your question regarding the communications
behaviors, but I don't see it on Github. Were you able to resolve the
problem?

**Comment by adamwoolhether** [comment]
Hey Adam. I really appreciate your attention to this!

Yes, I put the behaviors in the `demo/src/HyperviewScreen.tsx` file to get it working. Couldn't get it to work just using the `HyperviewScreen.js` example shown in the book.

But this is a deficit on my side more than anything: need to study how to build my own App with expo from scratch rather than relying on the  `hyperview/demo` app.

Got a fully-functioning implementation of book's Contact app, including the mobile aspect, with Go: https://github.com/adamwoolhether/hypermedia

Now to start building an actual thing what my new superpowers :D

**Comment by adamstep** [comment]
Very cool! Do you mind if I share this implementation more widely?

**Comment by adamwoolhether** [comment]
That would be an honor if you did. 👍🏼
