### ISSUE TITLE
The text contrast is too high

### ISSUE THREAD

**Issue by sharon-xa** [bigskysoftware/hypermedia-systems#138]
You have a dark background and a very bright text color, I'm gonna lose my eyes if keep reading the book using this website.
![bad-contrast](https://github.com/bigskysoftware/hypermedia-systems/assets/86781708/0e46e2ed-9569-4bb6-bc01-e01a2e9032c8)
![good-contrast](https://github.com/bigskysoftware/hypermedia-systems/assets/86781708/638360d5-5421-4b2b-8194-f6b882be7502)

I've changed the color using the dev tools and it's looking a lot calmer and more readable.

**Comment by scottstensland** [comment]
Many folks me included prefer a dark theme however your choice of practically solid black background makes my eyes zonkers ... at a minimum please give the book some toggle on color scheme

**Comment by 1cg** [comment]
Agree, we will try to make this adjustable in the future.  We are shutting down this repo in favor of a new one using a better typesetting tech but will address this once that repo is public.
