### ISSUE TITLE
Code blocks width on e-readers

### ISSUE THREAD

**Issue by imbolc** [bigskysoftware/hypermedia-systems#140]
Code blocks in the online version of the book do not fit on the screen of e-readers. This issue occurs even on A4 (13.3-inch) sized readers, as shown in the last screenshot.

I suggest:

- removing left padding
- reformatting code blocks to have a single attribute per line
- use 2-space tabs

![image](https://github.com/bigskysoftware/hypermedia-systems/assets/747996/83d92794-5235-4ada-9e58-767ac496ac6e)

![image](https://github.com/bigskysoftware/hypermedia-systems/assets/747996/528f731b-3a20-4bb4-adab-d386229eb655)

![image](https://github.com/bigskysoftware/hypermedia-systems/assets/747996/2a2ce9fa-9a08-4fd0-880a-2edc07040fc0)

**Comment by dz4k** [comment]
They're supposed to scroll horizontally -- are some ereaders not able to do this, or is it just too annoying? Either way, we can look into fixes.

**Comment by imbolc** [comment]
> They're supposed to scroll horizontally

Yes, they're scrollable

> or is it just too annoying?

At some level of complexity, you don't read code sequentially, which means constant back-and-forth scrolling.

**Comment by 1cg** [comment]
This will be improved in the next release of the book.
