### ISSUE TITLE
CSS transitions are possible without JS

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#18]
This is a really technical nit, but since this is a technical book I thought I'd mention it.

A couple of times in the book there's an incorrect statement about CSS transitions being unavailable / impossible without JS:

> Unfortunately, CSS transitions are not available in plain HTML

> it isn’t possible to use CSS transitions without using JavaScript.

As you'll see from the following link (ironically hosted at JS Fiddle but without JS), this isn't correct:
https://jsfiddle.net/elliottinvent/hL9pa1mk/10/

You guys are doing a great job.

**Comment by 1cg** [comment]
great point, thank you!
