### ISSUE TITLE
Chapter 12 / The Benefits of Using Your Own Client / Incorrect reference to HTMX

### ISSUE THREAD

**Issue by netaisllc** [bigskysoftware/hypermedia-systems#21]
As great as `htmx` is, and as wonderful a collaboration this book is, I do not think you want to refer to **HTMX** in the callout section.  See attached image; I will push a PR to cure.

(If I'm in the wrong, then apologies and urge you to use the conventional LowerCase usage of `htmx`.)

![Screen Shot 2023-01-08 at 6 49 23 PM](https://user-images.githubusercontent.com/1242423/211234151-c4232ec2-af01-4d09-bef5-a02cf33518e0.png)

**Comment by adamstep** [comment]
You are correct, this should be HXML. Thanks for catching!
