### ISSUE TITLE
URL defined as "Universal Resource Locator" instead of more commonly understood "Uniform Resource Locator"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#23]
In [2.1](https://hypermedia.systems/book/hypermedia-components/#_the_hypermedia) URL is defined as "Universal Resource Locator". I think this would be commonly seen by readers as a mistake, I recognise this is one old school meaning of URL but I'd suggest, either:

- use the commonly accepted Uniform Resource Locator definition; or
- make it obvious you are using the old-school term deliberately, especially if it supports the Hypermedia theme (it's not clear to me that it does)

**Comment by codetalcott** [comment]
I've made this change, but will leave the issue open to be sure 'universal' wasn't intentional.

**Comment by 1cg** [comment]
It was not intentional, thank you!
