### ISSUE TITLE
Standardise link style, perhaps so that it's suitable for print

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#27]
Some of the book has been written for print, with links written in a book style like this (ie the full URL in brackets):

> ... the most common approach today is to tie the DOM to a JavaScript model and then let an SPA framework like react (https://reactjs.org/) or vue (https://vuejs.org/) reactively update the DOM when a JavaScript model is updated ...

But other parts are written with hyperlinks which won't be suitable for print:

> Next we will look at how we can use [htmx](https://htmx.org/), a hypermedia-oriented JavaScript library, to improve Contact.app.

I'd suggest standardising on the first style.

**Comment by 1cg** [comment]
defer to @codetalcott on this, but I think we should use the standard link syntax

**Comment by dz4k** [comment]
In print, links are rendered as follows:
![Link text, then URL in small font in square brackets](https://user-images.githubusercontent.com/39595683/214949495-e7d18022-f026-4a5f-8d77-83d643413bd0.png)
So, the second style would be better IMO.

**Comment by elliottinvent** [comment]
If the print output renders the asciidoc links with the full URL, then I think that's the best of both worlds and agree with @dz4k

**Comment by codetalcott** [comment]
Good, glad I checked before creating more issues. 
Links should now all be in asciidoc link style.
