### ISSUE TITLE
Consider declaring vested interest before first mention of htmx and Hyperview

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#28]
There are over 500 mentions of `htmx` in the book (epic plugging!) and almost all of them come after the declaration of vested interest in Chapter 1:

> One such hypermedia oriented library is https://htmx.org[htmx], created by the authors of this book

Except for the one in the introduction:

> Next we will look at how we can use https://htmx.org[htmx], a hypermedia-oriented JavaScript library, to improve
  Contact.app.  By using htmx, we will be able to achieve a level of interactivity in our application that many developers
  would expect requires a large, sophisticated front end library, such as React.  Thanks to htmx, we will be able to do
  this _without_ abandoning hypermedia as a system architecture.

There are over 200 mentions of Hyperview and the declaration of vested interest in 12.2 comes before most of them:

> Hyperview, a new hypermedia format we designed specifically for mobile apps ...

But not all.

Perhaps the [Book Layout](https://hypermedia.systems/book/hypermedia-systems/#_book_layout) or elsewhere in the introduction could be the best place to declare these vested interests by the authors? 

I could understand you not wanting readers to think the entire book is a sales pitch, in case they abandon it in the introduction, but I think by the time they get to the book layout section you've done a really good job of piquing interest. 

Additionally, you could consider moving the "book layout" section to the end of the Introduction, after the "Hypermedia: A New Generation" so that you've really got them locked in before you declare interest. I'm not commenting on whether that re-order would still flow well, I'd need need to take a re-read to consider that.

**Comment by netaisllc** [comment]
@elliottinvent 100% agree.  It's a slippery slope but IMHO more credibility will be gained/retained by making the "vested interests" very obvious.

**Comment by 1cg** [comment]
I'm fine w/ this suggestion.  Do you mind putting a pull request together w/ suggested language?

**Comment by netaisllc** [comment]
FWIW I believe a good approach would be to create a new section, perhaps titled *About the Authors*, and place it at the end of the *Introduction* chapter.  The purpose of the content of the section is to handle the 'vested interest' aspect and the purpose of a dedicated section is to make the content more visible and easy to find.

By providing a brief "professional bio", each author will clearly be seen as an expert practitioner in the context of hypermedia systems. This will answer the unspoken question the reader has about any publication: _Why Should I listen To These Guys?_

And, moreover, it provides a super easy way to explain why **htmx**, **hyperscript**, and **Hyperview** are so prominent in the text.

Something along these lines:

> Throughout the book, we use the libraries X, Y, and Z to illustrate hypermedia concepts and to provide working examples of their implementation.  X, Y, and Z are used because we know them well, (heck, we wrote them!) but these tools have no special claim on hypermedia concepts or patterns. There, in fact, other libraries and packages (such as A, B, and even C) that elegantly implement hypermedia patterns and we encourage you to explore them as options for your hypermedia applications.

**Comment by elliottinvent** [comment]
I've added a simple short term fix for this in https://github.com/bigskysoftware/hypermedia-systems/pull/26 but I agree with the points made by @netaisllc. I think the change in the PR addresses the vested interest declaration but the best way to deal with the "oh, this is just a sales pitch" point is to make it clear you guys are an authority on the topic and y'know not just... err, memelords.

**Comment by 1cg** [comment]
closing for now
