### ISSUE TITLE
Consider standardising emphasis

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#29]
There are 19 instances of bold text being used in the book, e.g, the first is in the introduction: "That":

> It is important to understand that, in his dissertation, Fielding was describing The World Wide Web as it existed in the late 1990s. The Web, at that point, was simply web browsers exchanging hypermedia. **That** system, with its simple links and forms, was what Fielding was calling REST-ful

There are over 400 instances where italics are used, starting from the first paragraph:

> This is a book about building applications using hypermedia systems. _Hypermedia systems_ might seem like a strange phrase: how is hypermedia a _system_? Isn’t hypermedia just a way to link documents together?

There could be some reasoning as to why a small amount of text is emboldened and not italicised but it's not obvious to me. Unless there's a reason, I'd suggest switching it all to italics.

**Comment by codetalcott** [comment]
Agreed. I'll convert bold to italics, where it is used for emphasis

**Comment by codetalcott** [comment]
Bold for emphasis changed to italics
