### ISSUE TITLE
Unfinished sentence?

### ISSUE THREAD

**Issue by Arya-Elfren** [bigskysoftware/hypermedia-systems#3]
https://github.com/bigskysoftware/hypermedia-systems/blob/main/book/CH06_htmxPatterns.adoc

` This hx-boost attribute is unlike most other attributes in htmx: whereas other htmx attributes tend to be very focused on one aspect of improving HTML (e.g. hx-trigger focuses on the events that trigger a request, hx-swap focuses on how responses are swapped into the DOM, etc.) the hx-boost attribute, in contrast, is a high-level .`

is a high-level what?

**Comment by elliottinvent** [comment]
@1cg this was dealt with as part of https://github.com/bigskysoftware/hypermedia-systems/pull/15

And now reads: 
> This hx-boost attribute is unlike most other attributes in htmx: whereas other htmx attributes tend to be very focused on one aspect of improving HTML (e.g. hx-trigger focuses on the events that trigger a request, hx-swap focuses on how responses are swapped into the DOM, etc.) the hx-boost attribute, in contrast, is a high-level attribute

It was missing *attribute.*

So can be closed.

**Comment by 1cg** [comment]
thank you!
