### ISSUE TITLE
Consider moving / removing quote

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#31]
The first four quotes are:

- Terminator script
- Ted Nelson
- Timbl
- Our own @1cg

I like all of the quotes, but the haters (SPA boys) might jump on the author quoting himself.

**Comment by 1cg** [comment]
![image](https://user-images.githubusercontent.com/469183/213520758-80b43c66-05f3-435c-b0d5-655421412ea6.png)
