### ISSUE TITLE
Clarify "redundant server-side code" for noJS users

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#34]
The fantastic [progressive enhancement](https://hypermedia.systems/book/hypermedia-systems/#_progressive_enhancement_2) section says:

> One thing to note about this solution, however, is that it is not a progressive enhancement to our web application: if someone has disabled JavaScript then this “Delete Contact” button will no longer work. We could do additional work to keep the older mechanism working in a JavaScript-disabled environment, but this would introduce additional HTML and redundant server-side code.

I don't understand how it is "redundant server-side code" if it enables functionality to noJS users.

**Comment by netaisllc** [comment]
I bumped on this as well, and I agree with @elliottinvent.  The 'additional work' may be functionally equivalent to the client-side work but it serves (no pun) a different use case: no JS.

IMHO the book and the reader would be better served if the text end at "...Javascript-disabled environment."
