### ISSUE TITLE
Standardise "client-side" / "client side" and "server-side" / "server side"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#35]
There are:

- 64 instances of "server side"
- 23 instances of "server-side"

- 16 instances of "client side"
- 29 instances of "client-side"

If you decided on the hyphenated version, I'm sure there's instances that would be correct in the none hyphenated, e.g. if you were referring to something being "an app on the server side" rather than a "server-side app", but on my reading this seemed like an inconsistency.

**Comment by codetalcott** [comment]
Right. I'll edit to use the hyphen where appropriate.

**Comment by codetalcott** [comment]
In some cases it looks like 'server' or 'client' alone are a good fit, for example:
"a big part of any web app is validating the data that is submitted to the server side"
Should this just be 'to the server'?
Other examples:
"We'll need to update the server side to render empty content when the `DELETE` is issued"
"Now we can effectively trigger htmx requests from the server side."

**Comment by codetalcott** [comment]
I'll come back to this; standardize with 'server-side' as adjective, 'server side' as noun.

**Comment by elliottinvent** [comment]
> In some cases it looks like 'server' or 'client' alone are a good fit, for example:
"a big part of any web app is validating the data that is submitted to the server side"
Should this just be 'to the server'?
Other examples:
"We'll need to update the server side to render empty content when the DELETE is issued"
"Now we can effectively trigger htmx requests from the server side."

I don't think that change would make the text incorrect but it could be less precise, since although "validating the data that is submitted to the server side" is clearly talking about submitting data to the "server", in the context of a web app it's also talking about submitting data to the server side part of the web app. I think the same could be said for the two other examples.

**Comment by 1cg** [comment]
defer to @codetalcott on this, thank you!

**Comment by codetalcott** [comment]
Aiming for 'server-side' as adjective, 'server side' as noun.
