### ISSUE TITLE
Standardise spacing after a full stop / period

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#36]
I think different authors are using different styles for spacing after full stop / period / `.`! 

From what I can tell @1cg uses the more traditional double spacing and @adamstep and @dz4k use single spacing.

**Comment by dz4k** [comment]
> From what I can tell @1cg uses the more traditional double spacing and @adamstep and @dz4k use single spacing.

Yes, Adam and I do use correct spacing. It doesn't really matter though since Asciidoc normalizes spaces (and if it didn't, HTML would).
