### ISSUE TITLE
Introduce "toast messages"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#37]
It wasn't immediately clear to me what [toast messages](https://hypermedia.systems/book/hypermedia-systems/#_adding_toast_messages) are, so I think these need an introduction.

**Comment by netaisllc** [comment]
100%.  Could be referred to as notifications, alerts, app-messages, and other things. But the text should not assume the reader is familiar with what is actually an odd name.

**Comment by adamstep** [comment]
Thanks for the suggestions, will adopt a more common term.

**Comment by 1cg** [comment]
@adamstep can this be closed?

**Comment by adamstep** [comment]
yes, it's been fixed.
