### ISSUE TITLE
Standardise title case

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#39]
There's some inconsistency with title casing in the book, for exampe all of these are h3 titles:

> Showing A Searchable List Of Contacts
> Adding A New Contact
> Handling The Post to `/contacts/new`

And:

> VanillaJS in action: an overflow menu
> _hyperscript in action: a keyboard shortcut

I'll defer to @codetalcott on style

**Comment by dz4k** [comment]
Headings != titles, my vote is for sentence case

**Comment by 1cg** [comment]
defer to @codetalcott

**Comment by codetalcott** [comment]
I suggest (and am following) O'Reilly style guide:
- title case for A and B level headings
- sentence case for C level
- sentence case for example labels
- try to avoid code font in headings

**Comment by 1cg** [comment]
I like it!  Thank you!
