### ISSUE TITLE
Does word-breaking make it harder to read?

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#41]
My first reading of the book was on mobile, the second reading on desktop. 

This is a screenshot of a couple of the first paragraphs, notice "sophisticated", "ignore" and "applications" are needlessly broken across two lines and hyphenated:

<img width="757" alt="Screenshot 2023-01-12 at 22 24 16" src="https://user-images.githubusercontent.com/33970260/212193934-1e09f032-16d8-43aa-bf8d-7e0511a1ea50.png">

Mobile doesn't have this problem:

![IMG_7133](https://user-images.githubusercontent.com/33970260/212194404-f12aecd9-6752-447c-a6db-014eea88ddf8.PNG)

If anything I would say it makes more sense to have word-breaking on mobile, it seems pointless on desktop. Although I would argue for no word-breaks on either.

**Comment by 1cg** [comment]
@dz4k is this a CSS issue?

**Comment by dz4k** [comment]
The issue is not the device, but the browser. https://caniuse.com/css-hyphens shows that Safari requires a `-webkit-` prefix for `hyphens`. We can add this to achieve consistency.

I'm open to arguments on why the hyphenation is "unnecessary", I added it because it makes the line length more even and makes the text more compact. In the mobile screenshot above, big gaps can be seen next to "runtime and" and "these web".

(The book used to be set flush, but browsers are not great at justifying text).

**Comment by elliottinvent** [comment]
Fair point on “unnecessary” (have updated issue title) and the explanation for the inconsistency across browsers makes sense. 

If this text was in a book set flush, I don’t think the hyphens would look out of place. I’m not sure how it would look online “fully justified”, perhaps as though you were reading an ebook, which might be what you’re aiming for. However, as you say, this is difficult with browsers.  

For me at least, I found it harder to read with this word-breaking.

**Comment by dz4k** [comment]
A compromise: Enable word breaking if the screen is narrower than some amount. This should avoid extreme unevenness like that seen beside "runtime and".

Maybe we could take the longest word in the book (probably after eliminating some outliers) and multiply its width by 3 or so

**Comment by dz4k** [comment]
Looks like our longest word in terms of displayed size is "programmatically", some 14ch wide. Taking the rule above, hyphenation would be enabled for displays smaller than calc(14ch * 3 + page-margin). Does that sound reasonable?

**Comment by elliottinvent** [comment]
I've been noticing more hyphenated text on mobile since I raised this issue, I think the suggestion above makes a lot of sense. As I understand it, it would result in more hyphenation on mobile and effectively none on desktop which I think addresses this issue really well.

**Comment by dz4k** [comment]
Added the following CSS:

```css
    @media (max-width: calc(
        3 * /* arbitrary coefficient */
        14ch + /* longest word: programmatically*/
        2 * 1.6rem /* page margins */
    )) {
        :root {
            hyphens: auto;
            -webkit-hyphens: auto; /* safari :( */
        }
    }
```
