### ISSUE TITLE
Standardise on "The Web"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#42]
There is some inconsistency to how the book refers to this:

- 37 instances of the "The Web"
- 19 instances of "the Web"
- 100 or so instances of "the web", although some of these will be references to "the web site", "the web page", "the web application" 

The early chapters talk about "The Web" and I think this is a good style showing respect, since the book is all about building on top of this hypermedia system but will defer to @codetalcott

**Comment by codetalcott** [comment]
Good catch. I just came across this in the discussion of Tim Berners-Lee. I suggest going with current standard of 'the web.'

**Comment by codetalcott** [comment]
I suggest: go with 'the web' unless referring to 'Web 1.0.' 
In the following, I added '1.0' to fit this pattern. Does it read as intended?
"JSON APIs were a decade away from becoming a common tool in web development: REST was about _hypermedia_ and _the Web 1.0_."

**Comment by codetalcott** [comment]
I've standardized on 'the web' and 'the Web 1.0'; will keep this issue open

**Comment by elliottinvent** [comment]
I agree that "the web" makes sense generally and it seems widely accepted in that style now. I don't have strong feelings on how to refer to Web 1.0, but since the issue is open I'll add that this:

> "JSON APIs were a decade away from becoming a common tool in web development: REST was about hypermedia and the Web 1.0."

Could work better as:

> "JSON APIs were a decade away from becoming a common tool in web development: REST was about hypermedia and Web 1.0." (removing "the", referring to it as V1.0 of Something)

Or

> "JSON APIs were a decade away from becoming a common tool in web development: REST was about hypermedia and the The Web 1.0." (where Something is "The Web")

The other option in these cases could be to go with "the World Wide Web v1.0" or "WWW v1.0".

This isn't something I think is particularly important but thought it would be worth adding in some thoughts.

**Comment by 1cg** [comment]
I'm fine with this suggestion and capitalizing World Wide Web when we want to emphasize it
