### ISSUE TITLE
Is there a client-side / server-side mixup here?

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#43]
I could be misinterpreting this:

> Note also that, especially in web development parlance, the humble “server” is usually a whole fleet of racks, virtual machines, containers and more. Even a worldwide network of datacenters is reduced to “the server” when discussing the **client-side** of a Hypermedia Driven-Application.

(emphasis mine) 

But I'm pretty sure the emboldened text should read **server-side**

**Comment by netaisllc** [comment]
@elliottinvent I bumped on this one as well.  I actually think the sense of it is like this (I'm not proposing this text in any way):

"When considering a HDA application from the client standpoint, everything else is considered 'the server'" .

**Comment by 1cg** [comment]
agree, will fix

@elliottinvent can you include links to the page in question so it's easier to verify and edit?
