### ISSUE TITLE
Standardise on JavaScript

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#44]
In the book there is:

- 303 instances of "JavaScript"
- 11 of "Javascript"
- 3 of "javascript" (not in codeblocks)

Let's standardise to "JavaScript", beware that all lowercase `javascript` is used in codeblocks and updating these instances could cause problems with rendering.

**Comment by codetalcott** [comment]
Okay, changed to "JavaScript" except for codeblocks
