### ISSUE TITLE
Standardise HyperText / Hypertext

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#46]
In the book there's both `HyperText` and `Hypertext`. It has this inconsistency in common with the [Wikipedia page](https://en.wikipedia.org/wiki/Hypertext) which uses `Hypertext` mainly with a few scattered mentions of `HyperText`.

It could make sense to use `HyperText` when talking about it in the context of HTTP and HTML (both Wikipedia and the HS book use `HyperText` outside of these contexts), but it should probably be standardised in the book to one or the other.

**Comment by codetalcott** [comment]
I'll edit for lower caps; in some cases it looks like the 't' is capitalized to underscore its presence in 'http'
