### ISSUE TITLE
"Locality of Behaviour" or "Locality of Behavior"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#49]
This issue is based on a comment in [my PR that I just closed](https://github.com/bigskysoftware/hypermedia-systems/pull/10).

There are:

- 300+ mentions of "behavior" 
- two of "behaviour"

I would have considered this a typo (British English instead of American English) but both are in the [locality section in Chapter 10](https://hypermedia.systems/book/hypermedia-systems/#_locality), with one referring to a URL:
https://htmx.org/essays/locality-of-behaviour/

I think if that's the spelling of the LoB principle then that's fine (Rule Britannia! 🇬🇧) but it brings some inconsistency to the book.

(Incidentally, the page at that URL also has quite a bit of inconsistency too but realise that's out of the scope of the issues for this repo).

I'm not suggestion all mentions of behavior should be changed to the British English spelling, but it's important to note that @adamstep points out in the PR conversation:
> In the Hyperview chapters, behavior is a [keyword of the XML syntax](https://hyperview.org/docs/reference_behavior), so those should definitely not be changed! :)

**Comment by 1cg** [comment]
I have updated the essay to use the british "behaviour" everywhere, since I included it in the URL for that essay, and we can use that spelling for LoB in the book, but should use the US version elsewhere.  😑
