### ISSUE TITLE
Ch 13 - Editing a contact - Small copyedit

### ISSUE THREAD

**Issue by netaisllc** [bigskysoftware/hypermedia-systems#50]
Suggest adding a 's' to `make` for better style/flow:

![Screen Shot 2023-01-21 at 1 04 15 PM](https://user-images.githubusercontent.com/1242423/213887377-d3edd5c8-d553-4502-a8a3-89eee0f24a6b.png)

**Comment by adamstep** [comment]
Thanks, fixed in https://github.com/bigskysoftware/hypermedia-systems/commit/3ae3e82ca3fdf05ebc9de45b99b356ee7e3263e0.
