### ISSUE TITLE
Chapter 4 modal example outdated

### ISSUE THREAD

**Issue by mikewink** [bigskysoftware/hypermedia-systems#65]
Hi, I am reading the book and enjoy it a lot. Your arguments and facts really stick! Great way to get developers thinking and rethinking current (best) practices. 

While reading the conclusion of chapter 4, you write, there is no HTML API for creating modals. There is one now, in the form of the dialog element. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

I think, it would be good to revise the example and stick to the tabs example and a missing tabs element.

**Comment by dz4k** [comment]
The example was removed. Thanks for reporting.
