### ISSUE TITLE
Please clarify HTTP Repsonse Vary

### ISSUE THREAD

**Issue by nickchomey** [bigskysoftware/hypermedia-systems#68]
THis is from [Chapter 6](https://github.com/bigskysoftware/hypermedia-systems/blame/main/book/CH06_MorehtmxPatterns.adoc#L412) 

>The solution to this problem is to use the HTTP Response Vary header and call out the htmx headers that you are using to determine what content you are returning. A full explanation of HTTP Caching is beyond the scope of this book, but the [MDN article on the topic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching) is quite good, and the [htmx documentation](https://htmx.org/docs/#caching) discusses this issue as well.

There's no need to do a deep-dive into HTTP caching, but it would be great if you could add just a line or two about how to use `Vary` in this context. Likewise in the [HTMX docs](https://htmx.org/docs/#caching). Its not at all clear to me (even after consulting MDN) how to use it.

**Comment by 1cg** [comment]
Hi @nickchomey we will try to do so in the next release of the book.  We are closing down this repo in favor of a new one based on a different typesetting tool, so I will close this issue for now.
