### ISSUE TITLE
Link "Entire book in one page" is broken.

### ISSUE THREAD

**Issue by slkwrm** [bigskysoftware/hypermedia-systems#73]
Address: https://hypermedia.systems/book/contents/
Browser: Chromium v 113.0.5672.126

**Comment by gedw99** [comment]
same here :) 

The link is at the bottom of the page.


Its calls: 
https://hypermedia.systems/book/hypermedia-systems

 then redirects to: 

https://hypermedia.systems/book/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/hypermedia-systems/

**Comment by codetalcott** [comment]
Working link: ["Entire book in one page"](https://hypermedia.systems/hypermedia-systems/)
