### ISSUE TITLE
CH2 Self-descriptive messages has a broken header

### ISSUE THREAD

**Issue by bLaCkwEw** [bigskysoftware/hypermedia-systems#86]
I started reading the book, I'm now on chapter 2. I came across these random equal signs and I figured they're supposed to actually be a header.

![2023-07-08_21_27-09](https://github.com/bigskysoftware/hypermedia-systems/assets/35146970/34268578-a5cf-4817-849c-f708df5956d2)

**Comment by codetalcott** [comment]
Fixed. Thank you; that was a mis-formatted asciidoc 'index term' tag.
