### ISSUE TITLE
HTML title of "Entire book in one page" includes span tag

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#87]
https://hypermedia.systems/book/hypermedia-systems

```
<title>&lt;span class="allcaps big"&gt;Hypermedia Systems&lt;/span&gt;</title>
```

Possibly related issue that was previously closed: https://github.com/bigskysoftware/hypermedia-systems/issues/61

**Comment by sankalpmukim** [comment]
You are right, the commit was merged. Not sure why it's not visible on the website still. Will look into the source code
Edit: The corrected merged version is definitely present in the source code.
