### ISSUE TITLE
Is the source code for the app as it is developed through the book available in a repo?

### ISSUE THREAD

**Issue by pstaszko** [bigskysoftware/hypermedia-systems#93]
It would be nice to be able to review the code in it's entirety at various points throughout the book. Between the hardcover book, the web version, and the HTMX documentation. I'm finding it difficult to answer some of my own questions and having some full sets of working source could be a major help! I'm really enjoying the book, but the index at the back of the hardcover book is surprisingly bare too.
Lots of love though too, I'm super excited to work with this technology. I have landed on HTMX and F# for a rewrite of my corporate web portal.

**Comment by 1cg** [comment]
Unfortunately no, I didn't do a good job of keeping it clean.
