### ISSUE TITLE
What does JSON mean in the first HTMX response in the book?

### ISSUE THREAD

**Issue by juangiordana** [bigskysoftware/hypermedia-systems#94]
What does JSON mean in the first HTMX response in the book?

https://github.com/bigskysoftware/hypermedia-systems/blob/23afdf3732b12762db47420f4af16a1c29129ed9/book/CH01_HypermediaAReintroduction.adoc?plain=1#L629C3-L629C6

I assume this is an error, correct?

**Comment by mvolkmann** [comment]
Sure looks like an error to me. I wish I could fix it, but someone on the book team will have to do it.

**Comment by codetalcott** [comment]
Fixed, at last! Thank you.
