### ISSUE TITLE
ctrl + L example doesn't work

### ISSUE THREAD

**Issue by vikstrous2** [bigskysoftware/hypermedia-systems#99]
The example [here](https://hypermedia.systems/extending-html-as-hypermedia/#:~:text=loading%20the%20contacts%2C-,Ctrl%2DL%20(for%20%E2%80%9CLoad%E2%80%9D),-.%20To%20do%20this) doesn't work because:
1. `key == 'L'` seems to refer to shift + L rather than just the L button
2. Ctrl+L is captured by the browser and selects the URL bar
I was able to get it working by changing the filter to `key == 'l'`

**Comment by yardenshoham** [comment]
Fixed in https://github.com/bigskysoftware/hypermedia-systems/commit/f79e03243f7dff2092c8139e58e9bc06a5fc5189
